
### install REST Client extentions, before use this
### register
POST  http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "Andre",
    "email": "andreldm@gmail.com",
    "password": "7879",
    "confirmPassword": "7879"
}

### login
POST  http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "andreldm@gmail.com",
    "password": "7879"
}


### refresh token
GET  http://localhost:5000/api/token

### logout
DELETE   http://localhost:5000/logout

### get user
GET   http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6IkFuZHJlIiwiZW1haWwiOiJhbmRyZWxkbUBnbWFpbC5jb20iLCJpYXQiOjE2NzQ5MTc5MzAsImV4cCI6MTY3NDkxODkzMH0.TNMK2_-FIG9vD2s8HUd3UX_q3Oxk4mURH6rBEbTdpnA
### get list routes
GET   http://localhost:5000/apis
