
### install REST Client extentions, before use this
### register
POST  http://localhost:5000/register
Content-Type: application/json

{
    "name": "Andre",
    "email": "Andredd@gmail.com",
    "password": "7879",
    "confirmPassword": "7879"
}

### login
POST  http://localhost:5000/login
Content-Type: application/json

{
    "email": "andre@gmail.com",
    "password": "7879"
}


### refresh token
GET  http://localhost:5000/token

### logout
DELETE   http://localhost:5000/logout

### get user
GET   http://localhost:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFuZHJlXG4iLCJlbWFpbCI6ImFuZHJlQGdtYWlsLmNvbSIsImlhdCI6MTY3NDU2NTI1MCwiZXhwIjoxNjc0NTY2MjUwfQ.OOdpl0J1-y4oYazdDBrUdA71hiFHpMUgH0m0w_3RNX8