
### install REST Client extentions, before use this
### register
POST  http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "game2",
    "email": "andre2@gmail.com",
    "password": "1234",
    "confirm_password": "1234"
}

### login
POST  http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "andre2@gmail.com",
    "password": "1234"
}


### refresh token
GET  http://localhost:5000/api/token

### logout
DELETE   http://localhost:5000/logout

### get user
GET   http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6ImdhbWUyIiwiZW1haWwiOiJhbmRyZTJAZ21haWwuY29tIiwiaWF0IjoxNjkxNzA4MzMxLCJleHAiOjE2OTE3OTQ3MzF9.6sHc8MOWgC0vmsH1HjQcsNyF3MV1_e5Y3TIGtXSnjnU

### email verification 
GET   http://localhost:5000/api/email-verification/asdasd


### users 
GET   http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6ImdhbWUyIiwiZW1haWwiOiJhbmRyZTJAZ21haWwuY29tIiwiaWF0IjoxNjkxNzA4MzMxLCJleHAiOjE2OTE3OTQ3MzF9.6sHc8MOWgC0vmsH1HjQcsNyF3MV1_e5Y3TIGtXSnjnU

### users basic auth
GET   http://localhost:5000/api/users2
Authorization: Basic bXlCYXNpY1VzZXJuYW1lOm15QmFzaWNQYXNzd29yZA==
