
### install REST Client extentions, before use this
### register
POST  http://localhost:5000/api/register
Content-Type: application/json

{
    "name": "game",
    "email": "gamemain90@gmail.com",
    "password": "1234",
    "confirmPassword": "1234"
}

### login
POST  http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "gamemain90@gmail.com",
    "password": "1234"
}


### refresh token
GET  http://localhost:5000/api/token

### logout
DELETE   http://localhost:5000/logout

### get user
GET   http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IkFuZHJlIiwiZW1haWwiOiJhbmRyZTc4NzlAZ21haWwuY29tIiwiaWF0IjoxNjkwNzc0OTY5LCJleHAiOjE2OTA4NjEzNjl9.Aqae_13F9hSjgGlRfUas38D5ck8eyG_uefagnLSyBU4

### email verification 
GET   http://localhost:5000/api/email-verification/asdasd

### users no auth
GET   http://localhost:5000/api/users
