
### install REST Client extentions, before use this
### register
POST  https://nodemi.onrender.com/api/register
Content-Type: application/json

{
    "name": "Tester ",
    "email": "Tester@gmail.com",
    "password": "1234",
    "confirmPassword": "1234"
}

### login
POST  https://nodemi.onrender.com/api/login
Content-Type: application/json

{
    "email": "Tester@gmail.com",
    "password": "1234"
}


### refresh token
GET  https://nodemi.onrender.com/api/token

### logout
DELETE   http://localhost:5000/logout

### get user
GET   https://nodemi.onrender.com/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRlc3RlciAiLCJlbWFpbCI6IlRlc3RlckBnbWFpbC5jb20iLCJpYXQiOjE2OTE3MTA0MTIsImV4cCI6MTY5MTcxMTAxMn0.uufasynY26o7jBnV6IV_q4I1BgRej-E8mYg5rcKdJ6E

### get users
GET   https://nodemi.onrender.com/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlRlc3RlciAiLCJlbWFpbCI6IlRlc3RlckBnbWFpbC5jb20iLCJpYXQiOjE2OTE3MTA0MTIsImV4cCI6MTY5MTcxMTAxMn0.uufasynY26o7jBnV6IV_q4I1BgRej-E8mYg5rcKdJ6E

# ### users no auth
# GET   https://nodemi.onrender.com/api/users2
