
### install REST Client extentions, before use this
### register
POST  https://nodemi.onrender.com/api/register
Content-Type: application/json

{
    "name": "Tester",
    "email": "Tester@gmail.com",
    "password": "7879",
    "confirmPassword": "7879"
}

### login
POST  https://nodemi.onrender.com/api/login
Content-Type: application/json

{
    "email": "Tester@gmail.com",
    "password": "7879"
}


### refresh token
GET  https://nodemi.onrender.com/api/token

### logout
DELETE   http://localhost:5000/logout

### get user
GET   https://nodemi.onrender.com/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6IlRlc3RlciIsImVtYWlsIjoiVGVzdGVyQGdtYWlsLmNvbSIsImlhdCI6MTY3NjI4NDEwMiwiZXhwIjoxNjc2Mjg0NzAyfQ.wcSBK6xabYKDRATg8ai9O5ztI3-NDtZ-3-aiBasyIg0

### get users
GET   https://nodemi.onrender.com/api/users
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMsIm5hbWUiOiJBbmRyZSIsImVtYWlsIjoiYW5kcmVkZHNkZHNzQGdtYWlsLmNvbSIsImlhdCI6MTY3NjE5ODI4NywiZXhwIjoxNjc2Mjg0Njg3fQ.zDHjqitUJfZfh6SzHhaPvq6lliCfTt4dtebvYvcUQaI

### users no auth
GET   https://nodemi.onrender.com/api/users
